/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package core.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EXTYPE implements org.apache.thrift.TEnum {
  GENERAL_FAULT(1),
  TIMEOUT(2),
  SECURITY(3),
  STALENESS(4),
  BUSY(5),
  UNKNOWN(6);

  private final int value;

  private EXTYPE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EXTYPE findByValue(int value) { 
    switch (value) {
      case 1:
        return GENERAL_FAULT;
      case 2:
        return TIMEOUT;
      case 3:
        return SECURITY;
      case 4:
        return STALENESS;
      case 5:
        return BUSY;
      case 6:
        return UNKNOWN;
      default:
        return null;
    }
  }
}
