/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package dcell.agent.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OPERATION implements org.apache.thrift.TEnum {
  PING(1),
  GET(2),
  SET(3),
  DEL(4),
  SYS(5);

  private final int value;

  private OPERATION(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OPERATION findByValue(int value) { 
    switch (value) {
      case 1:
        return PING;
      case 2:
        return GET;
      case 3:
        return SET;
      case 4:
        return DEL;
      case 5:
        return SYS;
      default:
        return null;
    }
  }
}
